stateDiagram
  [*] --> waiting
  analysing_get_config_request
  analysing_get_config_request --> sending_get_config_response
  analysing_set_config_request
  analysing_set_config_request --> sending_set_config_response
  inspecting_packet
  inspecting_packet --> analysing_get_config_request
  inspecting_packet --> analysing_set_config_request
  scheduling_config_application
  scheduling_config_application --> waiting
  sending_get_config_response
  sending_get_config_response --> waiting
  sending_set_config_response
  sending_set_config_response --> scheduling_config_application
  sending_set_config_response --> waiting
  waiting
  waiting --> inspecting_packet
