stateDiagram
  [*] --> generating_inbound_local_schedules
  generating_global_schedules
  generating_global_schedules --> out_of_schedules
  generating_global_schedules --> proposing_global_schedules
  generating_inbound_local_schedules
  generating_inbound_local_schedules --> generating_outbound_local_schedules
  generating_inbound_local_schedules --> proposing_inbound_local_schedules
  generating_outbound_local_schedules
  generating_outbound_local_schedules --> generating_global_schedules
  generating_outbound_local_schedules --> proposing_outbound_local_schedules
  out_of_schedules
  out_of_schedules --> [*]
  proposing_global_schedules
  proposing_global_schedules --> [*]
  proposing_global_schedules --> out_of_schedules
  proposing_inbound_local_schedules
  proposing_inbound_local_schedules --> [*]
  proposing_inbound_local_schedules --> generating_outbound_local_schedules
  proposing_outbound_local_schedules
  proposing_outbound_local_schedules --> [*]
  proposing_outbound_local_schedules --> generating_global_schedules
