stateDiagram
  [*] --> waiting
  analysing_factory_heartbeat
  analysing_factory_heartbeat --> managing_resources
  analysing_factory_heartbeat --> waiting
  analysing_schedule_response
  analysing_schedule_response --> schedule_applied
  analysing_schedule_response --> schedule_not_applied
  applying_config
  applying_config --> waiting
  awaiting_schedule_response
  awaiting_schedule_response --> analysing_schedule_response
  awaiting_schedule_response --> schedule_not_applied
  changing_epoch
  changing_epoch --> waiting
  generating_schedule
  generating_schedule --> managing_resources
  generating_schedule --> sending_schedule
  inspecting_packet
  inspecting_packet --> analysing_factory_heartbeat
  inspecting_packet --> waiting
  managing_resource
  managing_resource --> generating_schedule
  managing_resources
  managing_resources --> managing_resource
  managing_resources --> waiting
  schedule_applied
  schedule_applied --> managing_resources
  schedule_not_applied
  schedule_not_applied --> generating_schedule
  schedule_not_applied --> managing_resources
  sending_schedule
  sending_schedule --> awaiting_schedule_response
  waiting
  waiting --> applying_config
  waiting --> changing_epoch
  waiting --> inspecting_packet
