stateDiagram
  [*] --> waiting
  analysing_declare_train_state
  analysing_declare_train_state --> enqueueing_declare_train_state
  analysing_marshal_identity_request
  analysing_marshal_identity_request --> sending_marshal_identity_response
  applying_config
  applying_config --> waiting
  changing_epoch
  changing_epoch --> waiting
  enqueueing_declare_train_state
  enqueueing_declare_train_state --> sending_declare_train_state_response
  inspecting_packet
  inspecting_packet --> analysing_declare_train_state
  inspecting_packet --> analysing_marshal_identity_request
  inspecting_packet --> waiting
  sending_declare_train_state_response
  sending_declare_train_state_response --> waiting
  sending_marshal_identity_response
  sending_marshal_identity_response --> waiting
  waiting
  waiting --> applying_config
  waiting --> changing_epoch
  waiting --> inspecting_packet
