stateDiagram
  [*] --> waiting
  analysing_current_release_request
  analysing_current_release_request --> sending_current_release_response
  analysing_reboot_request
  analysing_reboot_request --> rebooting
  analysing_update
  analysing_update --> testing_update
  applying_update
  applying_update --> broadcasting_reboot
  broadcasting_reboot
  broadcasting_reboot --> rebooting
  inspecting_packet
  inspecting_packet --> analysing_current_release_request
  inspecting_packet --> analysing_reboot_request
  inspecting_packet --> analysing_update
  rebooting
  rebooting --> [*]
  rejecting_update
  rejecting_update --> waiting
  sending_current_release_response
  sending_current_release_response --> waiting
  testing_update
  testing_update --> applying_update
  testing_update --> rejecting_update
  waiting
  waiting --> inspecting_packet
